### ISSUE TITLE
Path & filename is missing \ character to split the directory from the filename

### ISSUE THREAD

**Issue by Ferretaa** [stchan/CloneFinder#1]
When running CloneFinder.exe  Ver 1.2.1
The Paths output for duplicate files are merged with the filenames missing the \ character to delineate the path and the filename. This occurs regardless of if the csv options is selected.

**Comment by stchan** [comment]
See latest release (1.2.2)

**Comment by Ferretaa** [comment]
Thanks that's fixed the problem
