### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ivanstepanovftw** [stchan/CloneFinder#3]
Refusing to work, exception occurs after scan

**Comment by stchan** [comment]
tried to reproduce this - more details would be helpful

- Enivronment (OS, including build #, etc)
- How deep was the folder searched (depth, number of subfolders, files would be helpful). I tried it from a root directory that included several other file systems mounted on it, and didn't get a crash.
- As best as you can remember, the sequence of actions you took before the crash.

**Comment by stchan** [comment]
closing due to 30+ days of inactivity
